name: Build & Release

on:
    push:
        tags: ['v*']

permissions: write-all

jobs:
    deploy_macos:
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        with:
            file: | 
                ./dist/*.dmg
                ./dist/*mac.zip 
                ./dist/*.zip.blockmap 
                ./dist/latest-mac.yml
            runs-on: 'macos-latest'

    deploy_linux:
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        with:
            file: |
                ./dist/*.AppImage
                ./dist/latest-linux.yml
            runs-on: 'ubuntu-latest'

    deploy_windows:
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        with:
            file: |
                ./dist/*.exe
                ./dist/*.exe.blockmap
                ./dist/latest.yml
            runs-on: 'windows-latest'
